version: '3.3'

services:
   db:
     image: mysql:latest
     volumes:
       - ./db:/var/lib/mysql
     ports:
       - "3306:80"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: rootpass
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpresspass

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       -  ./sample-theme/:/var/www/html/wp-content/themes/main/
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpresspass
       WORDPRESS_DB_NAME: wordpress